// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZVJKwGSUEQuHJVqzC0A1NY3d4Ap1iyI',
    appId: '1:1071358971537:web:37155d21aaafe85776f930',
    messagingSenderId: '1071358971537',
    projectId: 'gemini-api-competetion',
    authDomain: 'gemini-api-competetion.firebaseapp.com',
    storageBucket: 'gemini-api-competetion.appspot.com',
    measurementId: 'G-SJ7CSK40ZP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJC_uH3UJ2rpX3HICAo3AwyIRBrcOc62Y',
    appId: '1:1071358971537:ios:899a41b3bc625fb176f930',
    messagingSenderId: '1071358971537',
    projectId: 'gemini-api-competetion',
    storageBucket: 'gemini-api-competetion.appspot.com',
    iosBundleId: 'com.example.fashionOrganiser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJC_uH3UJ2rpX3HICAo3AwyIRBrcOc62Y',
    appId: '1:1071358971537:ios:899a41b3bc625fb176f930',
    messagingSenderId: '1071358971537',
    projectId: 'gemini-api-competetion',
    storageBucket: 'gemini-api-competetion.appspot.com',
    iosBundleId: 'com.example.fashionOrganiser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbZVJKwGSUEQuHJVqzC0A1NY3d4Ap1iyI',
    appId: '1:1071358971537:web:c6b2758e66b0b1bc76f930',
    messagingSenderId: '1071358971537',
    projectId: 'gemini-api-competetion',
    authDomain: 'gemini-api-competetion.firebaseapp.com',
    storageBucket: 'gemini-api-competetion.appspot.com',
    measurementId: 'G-7DJX3EDY85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtI4SmDiJlSUiDcKhYPSK8oJ5sT0KaPdg',
    appId: '1:1071358971537:android:2b9f982c31eca55f76f930',
    messagingSenderId: '1071358971537',
    projectId: 'gemini-api-competetion',
    storageBucket: 'gemini-api-competetion.appspot.com',
  );

}